### ISSUE TITLE
加载好慢啊

### ISSUE THREAD

**Issue by wangxiaohuang007** [liudao01/cityList#1]
如何解决这个问题呢，加载差不多要4秒左右

**Comment by liudao01** [comment]
额  加载速度 只能这样了, 我也想尽办法优化过 , 如果你有心的话 可以把listview 替换成sectionlist.顺便说下这个加载速度是要先请求网络获得数据然后再渲染.

**Comment by wangxiaohuang007** [comment]
好吧。。
