### ISSUE TITLE
宽高问题

### ISSUE THREAD

**Issue by keernice** [liudao01/cityList#2]
// height 字母的高度间距
    // width 字母的宽度
    letter: {
        height: height * 3.3 / 100,
        width: width * 3 / 50,
        justifyContent: 'center',
        alignItems: 'center',
    }
请教，宽和高的计算方式怎样理解?

**Comment by liudao01** [comment]
好长时间了  记不太清楚了   你可以自己修改一下值 自己 尝试下

**Comment by keernice** [comment]
我自己的布局自定义的宽高值布局，没问题，但我这人儿就是很轴，为啥你的表达式计算出来的宽高相等，，很奇怪，想不通。。。。

**Comment by keernice** [comment]
隐隐约约中，我感觉到了知识点的存在

**Comment by liudao01** [comment]
我想 应该是 按照比例来的  高度是 3.3 / 100   宽度是3 / 50,
